ENABLE_TESTING()

ADD_SUBDIRECTORY(algorithm)
FILE(COPY algorithm DESTINATION ${CMAKE_CURRENT_BINARY_DIR})
ADD_SUBDIRECTORY(unsupported)
FILE(COPY unsupported DESTINATION ${CMAKE_CURRENT_BINARY_DIR})

IF(PYROL_ENABLE_NAVIER_STOKES)
  ADD_SUBDIRECTORY(navier_stokes)
  FILE(COPY navier_stokes DESTINATION ${CMAKE_CURRENT_BINARY_DIR})
ENDIF()

IF(PYROL_ENABLE_FLOW_OPT)
  ADD_SUBDIRECTORY(flow_opt)
  FILE(COPY flow_opt DESTINATION ${CMAKE_CURRENT_BINARY_DIR})
ENDIF()
