from __future__ import annotations

import argparse
import json
from pathlib import Path
import subprocess
import sys
from typing import Any

import numpy as np


ROOT = Path(__file__).resolve().parents[1]
PYTHON_DIR = ROOT / "python"
if str(PYTHON_DIR) not in sys.path:
    sys.path.insert(0, str(PYTHON_DIR))

from filtered_darcy_objective import FilteredDarcyObjective


DEFAULT_XML = ROOT / "Trilinos/packages/rol/example/PDE-OPT/flow-opt/axisymmetric/models/filteredDarcy/input.xml"
DEFAULT_MESH = ROOT / "tools/filtered_darcy_tiny_tri.txt"
DEFAULT_PROBE = (
    ROOT
    / "Trilinos/build/packages/rol/example/PDE-OPT/flow-opt/axisymmetric/models/filteredDarcy/rol_filtered_darcy_probe.exe"
)
DEFAULT_X = [0.5, 0.5, 0.5, 0.5]
DEFAULT_V = [0.21, -0.16, 0.07, -0.03]


def _parse_vector(text: str | None, default: list[float]) -> np.ndarray:
    if text is None:
        return np.asarray(default, dtype=float)
    cleaned = text.strip().strip("[]")
    if not cleaned:
        return np.zeros(0)
    return np.asarray([float(part) for part in cleaned.replace(";", ",").split(",")], dtype=float)


def _json_from_stdout(stdout: str) -> dict[str, Any]:
    for line in stdout.splitlines():
        stripped = line.strip()
        if stripped.startswith("{") and stripped.endswith("}"):
            return json.loads(stripped)
    raise ValueError(f"No JSON object found in C++ probe stdout:\n{stdout}")


def _run_cpp(probe: Path, xml: Path, mesh: Path, x: np.ndarray, v: np.ndarray) -> dict[str, Any]:
    command = [
        str(probe),
        "--input",
        str(xml),
        "--mesh",
        str(mesh),
        "--x",
        _format_vector(x),
        "--v",
        _format_vector(v),
    ]
    completed = subprocess.run(command, check=True, text=True, capture_output=True)
    return _json_from_stdout(completed.stdout)


def _run_cpp_check_vectors(probe: Path, xml: Path, mesh: Path) -> dict[str, Any]:
    command = [
        str(probe),
        "--input",
        str(xml),
        "--mesh",
        str(mesh),
        "--dump-check-vectors",
    ]
    completed = subprocess.run(command, check=True, text=True, capture_output=True)
    return _json_from_stdout(completed.stdout)


def _run_python(xml: Path, mesh: Path, x: np.ndarray, v: np.ndarray) -> dict[str, Any]:
    obj = FilteredDarcyObjective(xml, mesh_path=mesh)
    return {
        "density_size": obj.density_size,
        "parameter_size": obj.parameter_size,
        "value": obj.value(x),
        "gradient": obj.gradient(x).tolist(),
        "hess_vec": obj.hess_vec(x, v).tolist(),
    }


def _smooth_vectors(xml: Path, mesh: Path) -> tuple[np.ndarray, np.ndarray]:
    obj = FilteredDarcyObjective(xml, mesh_path=mesh)
    idx = np.arange(obj.density_size, dtype=float)
    density = 0.42 + 0.16 * np.sin(0.37 * (idx + 1.0)) + 0.05 * np.cos(0.19 * (idx + 1.0))
    direction = 0.09 * np.cos(0.23 * (idx + 1.0)) - 0.04 * np.sin(0.31 * (idx + 1.0))

    if obj.parameter_size:
        param = np.linspace(0.55, 0.48, obj.parameter_size)
        param_direction = np.linspace(0.03, -0.02, obj.parameter_size)
        density = np.concatenate([density, param])
        direction = np.concatenate([direction, param_direction])
    return density, direction


def _format_vector(values: np.ndarray) -> str:
    return "[" + ",".join(f"{float(value):.17e}" for value in values) + "]"


def _diff(name: str, py: Any, cpp: Any) -> tuple[float, float]:
    py_arr = np.atleast_1d(np.asarray(py, dtype=float))
    cpp_arr = np.atleast_1d(np.asarray(cpp, dtype=float))
    abs_diff = np.max(np.abs(py_arr - cpp_arr))
    rel_diff = abs_diff / max(1.0, float(np.max(np.abs(cpp_arr))))
    print(f"{name:10s} max_abs={abs_diff:.6e} max_rel={rel_diff:.6e}")
    return float(abs_diff), float(rel_diff)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Compare Python filtered Darcy objective against the ROL C++ probe.")
    parser.add_argument("--xml", type=Path, default=DEFAULT_XML)
    parser.add_argument("--mesh", type=Path, default=DEFAULT_MESH)
    parser.add_argument("--probe", type=Path, default=DEFAULT_PROBE)
    parser.add_argument("--x", type=str, default=None)
    parser.add_argument("--v", type=str, default=None)
    parser.add_argument("--auto-vectors", action="store_true", help="Use deterministic nonconstant vectors sized for the mesh.")
    parser.add_argument("--rol-check-vectors", action="store_true", help="Use rzp/dzp generated by the C++ probe's derivative-check setup.")
    parser.add_argument("--rtol", type=float, default=1e-10)
    parser.add_argument("--atol", type=float, default=1e-2)
    args = parser.parse_args(argv)

    xml = args.xml.expanduser().resolve()
    mesh = args.mesh.expanduser().resolve()
    probe = args.probe.expanduser().resolve()
    if args.rol_check_vectors:
        check_vectors = _run_cpp_check_vectors(probe, xml, mesh)
        x = np.asarray(check_vectors["rzp"], dtype=float)
        v = np.asarray(check_vectors["dzp"], dtype=float)
        print("ROL check vectors:", json.dumps(check_vectors, separators=(",", ":")))
    else:
        default_x = DEFAULT_X
        default_v = DEFAULT_V
        if args.auto_vectors:
            default_x_arr, default_v_arr = _smooth_vectors(xml, mesh)
            default_x = default_x_arr.tolist()
            default_v = default_v_arr.tolist()
        x = _parse_vector(args.x, default_x)
        v = _parse_vector(args.v, default_v)

    cpp = _run_cpp(probe, xml, mesh, x, v)
    py = _run_python(xml, mesh, x, v)

    print("C++:", json.dumps(cpp, separators=(",", ":")))
    print("Python:", json.dumps(py, separators=(",", ":")))
    diffs = [
        _diff("value", py["value"], cpp["value"]),
        _diff("gradient", py["gradient"], cpp["gradient"]),
        _diff("hess_vec", py["hess_vec"], cpp["hess_vec"]),
    ]
    ok = all(abs_diff <= args.atol or rel_diff <= args.rtol for abs_diff, rel_diff in diffs)
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
